### ISSUE TITLE
insertBefore needs 2 params in Chrome 38

### ISSUE THREAD

**Issue by hpoom** [nuragic/MastermindJS#2]
In Chrome 38 you get the following JS error on [kimbo.js line 346](https://github.com/nuragic/MastermindJS/blob/master/js/kimbo.js#L346)

`TypeError: Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.`

[It appears](https://code.google.com/p/chromium/issues/detail?id=419780) that the second param is not longer optional and explicit `null` needs to be passed in.

Pull request coming soon.

**Comment by nuragic** [comment]
Hi @hpoom,

Sorry for replying so late... Thanks for the PR! Anyway, I'm going to close it in favor of https://github.com/nuragic/MastermindJS/issues/4 

Sounds better?
